NewsSite/Areas/Administration/Controllers/EditorController.cs
namespace NewsSite.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using NewsSite.Models.Input;
    using NewsSite.Services;

    [Area("Administration")]
    [Authorize(Roles = "Administrator, Editor")]
    public class EditorController : Controller
    {
        private readonly IArticlesService articlesService;

        public EditorController(IArticlesService articlesService)
        {
            this.articlesService = articlesService;
        }

        public IActionResult Create()
        {
            return View(new CreateEditArticleInputModel());
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateEditArticleInputModel model)
        {
            if (ModelState.IsValid)
            {
                await articlesService.AddAsync(new
                CreateEditArticleInputModel
                {
                    Title = model.Title,
                    Author = model.Author,
                    Content = model.Content,
                    Subtitle = model.Subtitle,
                    ImageUrl = model.ImageUrl,
                    CategoryId = model.CategoryId,
                });

                return RedirectToAction("All");
            }

            return View(model);
        }

        public async Task<IActionResult> Delete(int id)
        {
            await articlesService.DeleteAsync(id);
            return RedirectToAction("All");
        }

        public async Task<IActionResult> Edit(int id)
        {
            var article = articlesService.GetByIdAsync(id);
            return View(
                "Create",
                new CreateEditArticleInputModel
                {
                    Id = article.Id,
                    Title = article.Title,
                    Author = article.Author,
                    Subtitle = article.Subtitle,
                    Content = article.Content,
                    ImageUrl = article.ImageUrl,
                    CategoryId = article.CategoryId
                });
        }

        [HttpPost]
        public async Task<IActionResult> Edit(CreateEditArticleInputModel model)
        {
            await articlesService.EditAsync(model);
            return RedirectToAction("All");
        }

        public async Task<IActionResult> All()
        {
            return View(await articlesService.GetAllAsync());
        }
    }
}

NewsSite/Controllers/EditorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using NewsSite.Models.Input;
using NewsSite.Services;

namespace NewsSite.Controllers
{
    [Authorize(Roles = "Administrator, Editor")]
    public class EditorController : Controller
    {
        private readonly IArticlesService articlesService;

        public EditorController(IArticlesService articlesService)
        {
            this.articlesService = articlesService;
        }

        public IActionResult Create()
        {
            return View(new CreateEditArticleInputModel());
        }

        [HttpPost]
        public IActionResult Create(CreateEditArticleInputModel model)
        {
            if (ModelState.IsValid)
            {
                articlesService.Add(new
                CreateEditArticleInputModel
                {
                    Title = model.Title,
                    Author = model.Author,
                    Content = model.Content,
                    Subtitle = model.Subtitle,
                    ImageUrl = model.ImageUrl,
                    CategoryId = model.CategoryId,
                });
                return RedirectToAction("All");
            }
            return View(model);
        }

        public IActionResult Delete(int id)
        {
            articlesService.Delete(id);
            return RedirectToAction("All");
        }

        public IActionResult Edit(int id)
        {
            var article = articlesService.GetById(id);
            return View("Create", new CreateEditArticleInputModel
            {
                Id = article.Id,
                Title = article.Title,
                Author = article.Author,
                Subtitle = article.Subtitle,
                Content = article.Content,
                ImageUrl = article.ImageUrl,
                CategoryId = article.CategoryId
            });
        }

        [HttpPost]
        public IActionResult Edit(CreateEditArticleInputModel model)
        {
            articlesService.Edit(model);
            return RedirectToAction("All");
        }

        public IActionResult All()
        {
            return View(articlesService.GetAll());
        }
    }
}

NewsSite/Areas/Administration/Views/Editor/All.cshtml
@using NewsSite.Services
@inject IArticlesService articlesService;
@{
    ViewData["Title"] = "All";
    var articles = await articlesService.GetAllAsync();
}

<form class="h-100" style="overflow-y: scroll;">
    <table class="table table-hover table-bordered table">
        <tr>
            <th>Id</th>
            <th>Заглавие</th>
            <th>Автор</th>
            <th>Създадена на</th>
            <th>Последна промяна</th>
            <th>Категория</th>
            <th>Действия</th>
        </tr>
        @foreach (var item in articles)
        {
            <tr>
                <td>@item.Id</td>
                <td>@item.Title</td>
                <td>@item.Author</td>
                <td>@item.CreatedOn.ToString("dd.MM.yyyy - HH:mm")</td>
                <td>@item.ModifiedOn.ToString("dd.MM.yyyy - HH:mm")</td>
                <td>@item.Category.Name</td>
                <td>
                    <div class="btn-group">
                        <button asp-controller="Editor" asp-action="Edit" asp-route-id="@item.Id" class="btn btn-primary">Промени</button>
                        <button asp-controller="Editor" asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger">Изтрий</button>
                    </div>
                </td>
            </tr>
        }

    </table>
</form>

NewsSite/Areas/Administration/Views/Editor/Create.cshtml
@model NewsSite.Models.Input.CreateEditArticleInputModel
@using NewsSite.Services
@using Ganss.XSS;
@inject ICategoryService categoryService;
@{
    ViewData["Title"] = "Create new article";
    var categories = await categoryService.GetAllAsync();
    var sanitizer = new HtmlSanitizer();
}

<form method="post" class="h-100" style="overflow-y: scroll;">
    <div>
        <label>Заглавие:</label><br />
        <input type="text" class="form-control" name="Title" value="@Model.Title" />
        <span asp-validation-for="Title" class="text-danger"></span>
    </div>

    <div>
        <label>Подзаглавие:</label><br />
        <input type="text" class="form-control" name="Subtitle" value="@Model.Subtitle" />
    </div>

    <div>
        <label>Автор:</label><br />
        <input type="text" class="form-control" name="Author" value="@Model.Author" />
        <span asp-validation-for="Author" class="text-danger"></span>
    </div>

    <div>
        <label>Линк на снимка:</label><br />
        <input type="text" class="form-control" name="ImageUrl" value="@Model.ImageUrl" />
        <span asp-validation-for="ImageUrl" class="text-danger"></span>
    </div>

    <div>
        <label>Категория:</label><br />
        <select class="form-control custom-select-sm" name="CategoryId">
            @foreach (var category in categories)
            {
                @if (Model.CategoryId == category.Id)
                {
                    <option value="@category.Id" selected>@category.Name</option>
                }
                else
                {
                    <option value="@category.Id">@category.Name</option>
                }
            }
        </select>
        <span asp-validation-for="CategoryId" class="text-danger"></span>
    </div>
    <div>
        <label>Съдържание:</label><br />
        <textarea class="form-control" rows="25" name="Content">@Html.Raw(sanitizer.Sanitize(Model.Content))</textarea>
        <span asp-validation-for="Content" class="text-danger"></span>
    </div>

    <hr />
    <div>
        <input type="submit" class="btn btn-primary" value="Добави" />
    </div>
</form>

<script src="https://cdn.tiny.cloud/1/no-api-key/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
<script>tinymce.init({ selector: 'textarea' });</script>

NewsSite/Areas/Administration/Views/Editor/Index.cshtml
@using NewsSite.Services
@inject IArticlesService articlesService;
@{
    ViewData["Title"] = "All";
    var articles = articlesService.GetAll();
}

<form class="h-100" style="overflow-y: scroll;">
    <table class="table table-hover table-bordered table">
        <tr>
            <th>Id</th>
            <th>Заглавие</th>
            <th>Автор</th>
            <th>Създадена на</th>
            <th>Последна промяна</th>
            <th>Категория</th>
            <th>Действия</th>
        </tr>
        @foreach (var item in articles)
        {
            <tr>
                <td>@item.Id</td>
                <td>@item.Title</td>
                <td>@item.Author</td>
                <td>@item.CreatedOn.ToString("dd.MM.yyyy - HH:mm")</td>
                <td>@item.ModifiedOn.ToString("dd.MM.yyyy - HH:mm")</td>
                <td>@item.Category.Name</td>
                <td>
                    <div class="btn-group">
                        <button asp-controller="Editor" asp-action="Edit" asp-route-id="@item.Id" class="btn btn-primary">Промени</button>
                        <button asp-controller="Editor" asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger">Изтрий</button>
                    </div>
                </td>
            </tr>
        }

    </table>
</form>