NewsSite/Models/Data/Category.cs
namespace NewsSite.Models.Data
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;

    public class Category
    {
        public Category()
        {
            this.Articles = new HashSet<Article>();
        }

        public int Id { get; set; }

        public string Name { get; set; }

        public string Description { get; set; }

        public virtual ICollection<Article> Articles { get; set; }
    }
}

NewsSite/Controllers/ArticlesController.cs
namespace NewsSite.Controllers
{
    using System;
    using System.Security.Claims;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
    using Microsoft.AspNetCore.Mvc;
    using NewsSite.Models.Data;
    using NewsSite.Models.Input;
    using NewsSite.Models.View;
    using NewsSite.Services;

    public class ArticlesController : Controller
    {
        private readonly IArticlesService articlesService;
        private readonly ICommentsService commentsService;
        private readonly UserManager<IdentityUser> userManager;

        public ArticlesController(IArticlesService articlesService, ICommentsService commentsService, UserManager<IdentityUser> userManager)
        {
            this.articlesService = articlesService;
            this.commentsService = commentsService;
            this.userManager = userManager;
        }

        [AllowAnonymous]
        [HttpGet]
        public async Task<IActionResult> Id(int id)
        {
            var article = articlesService.GetByIdAsync(id);
            if (article == null)
            {
                return View("ErrorStatus", 404);
            }

            await articlesService.IncreaseViewsAsync(id);
            var result = new ArticleViewModel()
            {
                Id = article.Id,
                Title = article.Title,
                Subtitle = article.Subtitle,
                Author = article.Author,
                CreatedOn = article.CreatedOn,
                Content = article.Content,
                Views = article.Views,
                ImageUrl = article.ImageUrl,
                CategoryId = article.CategoryId,
                Category = article.Category,
                Comments = article.Comments
            };

            return View(result);
        }

        [HttpPost]
        [Authorize(Roles = "Administrator, Editor, Member")]
        public async Task<IActionResult> Id(int id, string commentContent)
        {
            var result = new CreateEditCommentInputModel
            {
                ArticleId = id,
                Content = commentContent,
                User = await userManager.GetUserAsync(this.HttpContext.User),
            };
            await commentsService.CreateAsync(result);
            return Redirect(string.Concat(id, "#comments"));
        }

        [Authorize(Roles = "Administrator, Moderator")]
        public async Task<IActionResult> DeleteComment(int articleId, int commentId)
        {
            await commentsService.DeleteAsync(commentId);
            return Redirect(string.Concat("Id/", articleId, "#comments"));
        }
    }
}

NewsSite/Controllers/CategoriesController.cs
namespace NewsSite.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Mvc;
    using NewsSite.Services;

    public class CategoriesController : Controller
    {
        private readonly ICategoryService categoryService;

        public CategoriesController(ICategoryService categoryService)
        {
            this.categoryService = categoryService;
        }

        public async Task<IActionResult> Index(string name)
        {
            var result = await categoryService.GetByNameAsync(name, true);
            if (result == null)
            {
                return View("ErrorStatus", 404);
            }

            return View(result);
        }
    }
}

NewsSite/ViewComponents/SearchViewComponent.cs
namespace NewsSite.ViewComponents
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Mvc;

    [ViewComponent(Name = "Search")]
    public class SearchViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync()
        {
            return View();
        }
    }
}

NewsSite/ViewComponents/TopArticlesViewComponent.cs
namespace NewsSite.ViewComponents
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Mvc;
    using NewsSite.Models.View;
    using NewsSite.Services;

    [ViewComponent(Name = "TopArticles")]
    public class TopArticlesViewComponent : ViewComponent
    {
        private readonly IArticlesService articlesService;

        public TopArticlesViewComponent(IArticlesService articlesService)
        {
            this.articlesService = articlesService;
        }

        public async Task<IViewComponentResult> InvokeAsync(int count)
        {
            var articles = await articlesService
                .GetAllAsync();
            var topRead = articles
                .OrderByDescending(x => x.Views)
                .Take(count)
                .ToList();
            var topCommented = articles
                .Where(x => x.Comments.Count() > 0)
                .OrderByDescending(x => x.Comments.Count())
                .Take(count)
                .ToList();

            var resultModel = new TopArticlesViewModel
            {
                TopRead = topRead,
                TopCommented = topCommented
            };

            return View(resultModel);
        }
    }
}

NewsSite/Views/Categories/Index.cshtml
@model NewsSite.Models.Data.Category
@using Ganss.XSS;
@using Microsoft.AspNetCore.Identity
@{
    var sanitizer = new HtmlSanitizer();
    ViewData["Title"] = @Model.Name;
    var articles = Model.Articles.OrderByDescending(x => x.CreatedOn).ToList();
}

<div class="container">
    <div class="container-fluid p-0 mt-1 mb-3">

        <div class="col-9 pr-2 pl-0 float-left leftColumn">
            <div class="row w-100">
                @if (Model.Articles.Count == 0)
                {
                    <h1>Няма намерени материали</h1>
                }
                @foreach (var item in articles)
                {
                    <div class="card w-100 my-2">
                        <div class="row no-gutters">
                            <div class="col-auto">
                                <img src="@item.ImageUrl" class="img-fluid" style="width: 200px; height:200px;  object-fit: cover; object-position: 50% 0;">
                            </div>
                            <div class="col h-100">
                                <div class="card-block px-2">
                                    <h4 class="card-title">@item.Title</h4>
                                    <p class="card-text">@item.Subtitle</p>
                                    @if (item.Content.Length >= 300)
                                    {
                                        <p class="card-text">@Html.Raw(sanitizer.Sanitize(@item.Content.Substring(0, 300) + "..."))</p>
                                    }
                                    else
                                    {
                                        <p class="card-text">@Html.Raw(sanitizer.Sanitize(@item.Content + "..."))</p>
                                    }
                                    <i class="far fa-clock"></i>
                                    @item.CreatedOn.ToString("dd.MM.yyyy | HH:mm") |
                                    <i class="far fa-comment-dots"></i>
                                    @item.Comments.Count()
                                </div>
                            </div>
                        </div>
                        <a class="stretched-link" asp-controller="Articles" asp-action="Id" asp-route-id="@item.Id"></a>
                    </div>
                }
            </div>
        </div>
        <div class="col-3 p-0 float-right mobile-element rightColumn">
            <vc:search></vc:search>
            <vc:top-articles count="10"></vc:top-articles>
        </div>
    </div>

</div>